spring.application.name=bff-usuarios-roles
server.port=8081
roles.function.url=${ROLES_FUNCTION_URL:http://localhost:7071/api/roles}
usuarios.function.url=${USUARIOS_FUNCTION_URL:http://localhost:7072/api/usuarios}